// @flow

export const PREVIEW_CONTENT_UPDATE_EVENT = 'PREVIEW_CONTENT_UPDATE_EVENT';
export const PREVIEW_TAB_POLL_EVENT = 'PREVIEW_TAB_POLL_EVENT';
export const PREVIEW_TAB_POLL_RECEIVED_EVENT = 'PREVIEW_TAB_POLL_RECEIVED_EVENT';
export const PREVIEW_HOVERED_BLOCK_UPDATE_EVENT = 'PREVIEW_HOVERED_BLOCK_UPDATE_EVENT';

export const PREVIEW_BLOCK_HOVERED_CLIENT_RECT = 'PREVIEW_BLOCK_HOVERED_CLIENT_RECT';
export const PREVIEW_IFRAME_BROADCAST_INIT = 'PREVIEW_IFRAME_BROADCAST_INIT';
export const PREVIEW_IFRAME_ROUTE_CHANGED = 'PREVIEW_IFRAME_ROUTE_CHANGED';
